# This file is for testing purposes only

version: '3'
services:
  django:
    build:
      context: ./django
    volumes:
      -  "c:/Users/Cailan/Documents/SENG_499/cumulus_test_workspace:/cumulus"
    environment:
      CUMULUS_MODE: ${CUMULUS_MODE}
    ports:
      - "8080:8080"
  mysql:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "3306"
