# This file is for testing purposes only

version: '3'
services:
  django:
    build:
      context: ./django
    volumes:
      -  "c:/Users/Cailan/Documents/SENG_499/cumulus_test_workspace/django:/cumulus/django"
    ports:
      - "8080:8080"
    environment:
      CUMULUS_MODE: START
  mysql:
    build:
      context: ./mysql
    command: [ "mysqld" ]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      CUMULUS_MODE: START
    ports:
      - "3306"
    volumes:
      -  "c:/Users/Cailan/Documents/SENG_499/cumulus_test_workspace/mysql:/cumulus/mysql"
