# This file is for testing purposes

version: '3.2'
services:
  web_app:
    build:
      context: .
    volumes:
      -  "c:/Users/Cailan/Documents/SENG_499/cumulus_test_workspace:/cumulus"
    environment:
      CUMULUS_MODE: INIT
